// Code generated by schema-to-code generator. DO NOT EDIT.
// Source: ref schema tables
// Generated: Auto-generated from database schema with LASANI compliance

package models

import (
	"time"
	"github.com/google/uuid"
)

// Country represents ref.countries table with complete LASANI audit compliance
type Country struct {
	// PRIMARY KEY (1 field)
	CountryID uuid.UUID `json:"country_id" db:"country_id" gorm:"primaryKey;type:uuid;default:gen_random_uuid()"`
	
	// BUSINESS IDENTITY (2 fields)
	CountryCode string `json:"country_code" db:"country_code" gorm:"uniqueIndex;size:2;not null" validate:"required,len=2"`
	CountryName string `json:"country_name" db:"country_name" gorm:"size:100;not null" validate:"required,max=100"`
	
	// BUSINESS PROPERTIES
	ISO3Code     *string `json:"iso3_code,omitempty" db:"iso3_code" gorm:"uniqueIndex;size:3"`
	NumericCode  *int16  `json:"numeric_code,omitempty" db:"numeric_code" gorm:"uniqueIndex"`
	OfficialName *string `json:"official_name,omitempty" db:"official_name" gorm:"size:200"`
	CapitalCity  *string `json:"capital_city,omitempty" db:"capital_city" gorm:"size:100"`
	ContinentCode *string `json:"continent_code,omitempty" db:"continent_code" gorm:"size:2"`
	RegionCode   *string `json:"region_code,omitempty" db:"region_code" gorm:"size:10"`
	CurrencyCode *string `json:"currency_code,omitempty" db:"currency_code" gorm:"size:3"`
	PhonePrefix  *string `json:"phone_prefix,omitempty" db:"phone_prefix" gorm:"size:10"`
	
	// STATUS MANAGEMENT (2 fields)
	IsActive  bool `json:"is_active" db:"is_active" gorm:"default:true;not null;index"`
	IsDeleted bool `json:"is_deleted" db:"is_deleted" gorm:"default:false;not null;index"`
	
	// LASANI AUDIT FIELDS (21 fields)
	// Creation tracking (6 fields)
	CreatedAt       *time.Time `json:"created_at,omitempty" db:"created_at" gorm:"default:now()"`
	CreatedBy       *uuid.UUID `json:"created_by,omitempty" db:"created_by"`
	CreatedIP       *string    `json:"created_ip,omitempty" db:"created_ip" gorm:"type:inet"`
	CreatedDevice   *string    `json:"created_device,omitempty" db:"created_device" gorm:"type:jsonb"`
	CreatedSession  *uuid.UUID `json:"created_session,omitempty" db:"created_session"`
	CreatedLocation *string    `json:"created_location,omitempty" db:"created_location" gorm:"type:jsonb"`
	
	// Update tracking (6 fields)
	UpdatedAt       *time.Time `json:"updated_at,omitempty" db:"updated_at" gorm:"default:now()"`
	UpdatedBy       *uuid.UUID `json:"updated_by,omitempty" db:"updated_by"`
	UpdatedIP       *string    `json:"updated_ip,omitempty" db:"updated_ip" gorm:"type:inet"`
	UpdatedDevice   *string    `json:"updated_device,omitempty" db:"updated_device" gorm:"type:jsonb"`
	UpdatedSession  *uuid.UUID `json:"updated_session,omitempty" db:"updated_session"`
	UpdatedLocation *string    `json:"updated_location,omitempty" db:"updated_location" gorm:"type:jsonb"`
	
	// Deletion tracking (6 fields)
	DeletedAt       *time.Time `json:"deleted_at,omitempty" db:"deleted_at"`
	DeletedBy       *uuid.UUID `json:"deleted_by,omitempty" db:"deleted_by"`
	DeletedIP       *string    `json:"deleted_ip,omitempty" db:"deleted_ip" gorm:"type:inet"`
	DeletedDevice   *string    `json:"deleted_device,omitempty" db:"deleted_device" gorm:"type:jsonb"`
	DeletedSession  *uuid.UUID `json:"deleted_session,omitempty" db:"deleted_session"`
	DeletedLocation *string    `json:"deleted_location,omitempty" db:"deleted_location" gorm:"type:jsonb"`
	
	// System metadata (3 fields)
	SourceSystem  string  `json:"source_system" db:"source_system" gorm:"size:50;default:reference_master"`
	ChangeReason  *string `json:"change_reason,omitempty" db:"change_reason" gorm:"type:text"`
	
	// VERSION CONTROL (1 field)
	Version int `json:"version" db:"version" gorm:"default:1;not null"`
	
	// TOTAL: 27 fields (1+2+2+21+1) ✅
}

// Region represents ref.regions table with complete LASANI audit compliance
type Region struct {
	// PRIMARY KEY
	RegionID uuid.UUID `json:"region_id" db:"region_id" gorm:"primaryKey;type:uuid;default:gen_random_uuid()"`
	
	// BUSINESS IDENTITY
	RegionCode string `json:"region_code" db:"region_code" gorm:"uniqueIndex;size:10;not null" validate:"required,max=10"`
	RegionName string `json:"region_name" db:"region_name" gorm:"size:100;not null" validate:"required,max=100"`
	
	// BUSINESS PROPERTIES
	RegionType       *string    `json:"region_type,omitempty" db:"region_type" gorm:"size:20"`
	ParentRegionID   *uuid.UUID `json:"parent_region_id,omitempty" db:"parent_region_id"`
	
	// STATUS MANAGEMENT
	IsActive  bool `json:"is_active" db:"is_active" gorm:"default:true;not null;index"`
	IsDeleted bool `json:"is_deleted" db:"is_deleted" gorm:"default:false;not null;index"`
	
	// COMPLETE LASANI AUDIT FIELDS (21 fields)
	CreatedAt       *time.Time `json:"created_at,omitempty" db:"created_at" gorm:"default:now()"`
	CreatedBy       *uuid.UUID `json:"created_by,omitempty" db:"created_by"`
	CreatedIP       *string    `json:"created_ip,omitempty" db:"created_ip" gorm:"type:inet"`
	CreatedDevice   *string    `json:"created_device,omitempty" db:"created_device" gorm:"type:jsonb"`
	CreatedSession  *uuid.UUID `json:"created_session,omitempty" db:"created_session"`
	CreatedLocation *string    `json:"created_location,omitempty" db:"created_location" gorm:"type:jsonb"`
	
	UpdatedAt       *time.Time `json:"updated_at,omitempty" db:"updated_at" gorm:"default:now()"`
	UpdatedBy       *uuid.UUID `json:"updated_by,omitempty" db:"updated_by"`
	UpdatedIP       *string    `json:"updated_ip,omitempty" db:"updated_ip" gorm:"type:inet"`
	UpdatedDevice   *string    `json:"updated_device,omitempty" db:"updated_device" gorm:"type:jsonb"`
	UpdatedSession  *uuid.UUID `json:"updated_session,omitempty" db:"updated_session"`
	UpdatedLocation *string    `json:"updated_location,omitempty" db:"updated_location" gorm:"type:jsonb"`
	
	DeletedAt       *time.Time `json:"deleted_at,omitempty" db:"deleted_at"`
	DeletedBy       *uuid.UUID `json:"deleted_by,omitempty" db:"deleted_by"`
	DeletedIP       *string    `json:"deleted_ip,omitempty" db:"deleted_ip" gorm:"type:inet"`
	DeletedDevice   *string    `json:"deleted_device,omitempty" db:"deleted_device" gorm:"type:jsonb"`
	DeletedSession  *uuid.UUID `json:"deleted_session,omitempty" db:"deleted_session"`
	DeletedLocation *string    `json:"deleted_location,omitempty" db:"deleted_location" gorm:"type:jsonb"`
	
	SourceSystem  string  `json:"source_system" db:"source_system" gorm:"size:50;default:reference_master"`
	ChangeReason  *string `json:"change_reason,omitempty" db:"change_reason" gorm:"type:text"`
	Version       int     `json:"version" db:"version" gorm:"default:1;not null"`
}

// Timezone represents ref.timezones table with complete LASANI audit compliance
type Timezone struct {
	// PRIMARY KEY
	TimezoneID uuid.UUID `json:"timezone_id" db:"timezone_id" gorm:"primaryKey;type:uuid;default:gen_random_uuid()"`
	
	// BUSINESS IDENTITY
	TimezoneCode string `json:"timezone_code" db:"timezone_code" gorm:"uniqueIndex;size:50;not null" validate:"required,max=50"`
	TimezoneName string `json:"timezone_name" db:"timezone_name" gorm:"size:100;not null" validate:"required,max=100"`
	
	// BUSINESS PROPERTIES
	UTCOffsetHours   int16  `json:"utc_offset_hours" db:"utc_offset_hours" gorm:"not null"`
	UTCOffsetMinutes int16  `json:"utc_offset_minutes" db:"utc_offset_minutes" gorm:"default:0"`
	SupportsDST      bool   `json:"supports_dst" db:"supports_dst" gorm:"default:false"`
	DSTOffsetHours   *int16 `json:"dst_offset_hours,omitempty" db:"dst_offset_hours"`
	
	// STATUS MANAGEMENT + COMPLETE LASANI AUDIT FIELDS (23 fields)
	IsActive  bool `json:"is_active" db:"is_active" gorm:"default:true;not null;index"`
	IsDeleted bool `json:"is_deleted" db:"is_deleted" gorm:"default:false;not null;index"`
	
	CreatedAt       *time.Time `json:"created_at,omitempty" db:"created_at" gorm:"default:now()"`
	CreatedBy       *uuid.UUID `json:"created_by,omitempty" db:"created_by"`
	CreatedIP       *string    `json:"created_ip,omitempty" db:"created_ip" gorm:"type:inet"`
	CreatedDevice   *string    `json:"created_device,omitempty" db:"created_device" gorm:"type:jsonb"`
	CreatedSession  *uuid.UUID `json:"created_session,omitempty" db:"created_session"`
	CreatedLocation *string    `json:"created_location,omitempty" db:"created_location" gorm:"type:jsonb"`
	
	UpdatedAt       *time.Time `json:"updated_at,omitempty" db:"updated_at" gorm:"default:now()"`
	UpdatedBy       *uuid.UUID `json:"updated_by,omitempty" db:"updated_by"`
	UpdatedIP       *string    `json:"updated_ip,omitempty" db:"updated_ip" gorm:"type:inet"`
	UpdatedDevice   *string    `json:"updated_device,omitempty" db:"updated_device" gorm:"type:jsonb"`
	UpdatedSession  *uuid.UUID `json:"updated_session,omitempty" db:"updated_session"`
	UpdatedLocation *string    `json:"updated_location,omitempty" db:"updated_location" gorm:"type:jsonb"`
	
	DeletedAt       *time.Time `json:"deleted_at,omitempty" db:"deleted_at"`
	DeletedBy       *uuid.UUID `json:"deleted_by,omitempty" db:"deleted_by"`
	DeletedIP       *string    `json:"deleted_ip,omitempty" db:"deleted_ip" gorm:"type:inet"`
	DeletedDevice   *string    `json:"deleted_device,omitempty" db:"deleted_device" gorm:"type:jsonb"`
	DeletedSession  *uuid.UUID `json:"deleted_session,omitempty" db:"deleted_session"`
	DeletedLocation *string    `json:"deleted_location,omitempty" db:"deleted_location" gorm:"type:jsonb"`
	
	SourceSystem  string  `json:"source_system" db:"source_system" gorm:"size:50;default:reference_master"`
	ChangeReason  *string `json:"change_reason,omitempty" db:"change_reason" gorm:"type:text"`
	Version       int     `json:"version" db:"version" gorm:"default:1;not null"`
}

// Language represents ref.languages table with complete LASANI audit compliance
type Language struct {
	// PRIMARY KEY
	LanguageID uuid.UUID `json:"language_id" db:"language_id" gorm:"primaryKey;type:uuid;default:gen_random_uuid()"`
	
	// BUSINESS IDENTITY
	LanguageCode string `json:"language_code" db:"language_code" gorm:"uniqueIndex;size:2;not null" validate:"required,len=2"`
	LanguageName string `json:"language_name" db:"language_name" gorm:"size:100;not null" validate:"required,max=100"`
	
	// BUSINESS PROPERTIES
	ISO3Code   *string `json:"iso3_code,omitempty" db:"iso3_code" gorm:"size:3"`
	NativeName *string `json:"native_name,omitempty" db:"native_name" gorm:"size:100"`
	Direction  string  `json:"direction" db:"direction" gorm:"size:3;default:LTR" validate:"oneof=LTR RTL"`
	
	// STATUS MANAGEMENT + COMPLETE LASANI AUDIT FIELDS (23 fields)
	IsActive  bool `json:"is_active" db:"is_active" gorm:"default:true;not null;index"`
	IsDeleted bool `json:"is_deleted" db:"is_deleted" gorm:"default:false;not null;index"`
	
	CreatedAt       *time.Time `json:"created_at,omitempty" db:"created_at" gorm:"default:now()"`
	CreatedBy       *uuid.UUID `json:"created_by,omitempty" db:"created_by"`
	CreatedIP       *string    `json:"created_ip,omitempty" db:"created_ip" gorm:"type:inet"`
	CreatedDevice   *string    `json:"created_device,omitempty" db:"created_device" gorm:"type:jsonb"`
	CreatedSession  *uuid.UUID `json:"created_session,omitempty" db:"created_session"`
	CreatedLocation *string    `json:"created_location,omitempty" db:"created_location" gorm:"type:jsonb"`
	
	UpdatedAt       *time.Time `json:"updated_at,omitempty" db:"updated_at" gorm:"default:now()"`
	UpdatedBy       *uuid.UUID `json:"updated_by,omitempty" db:"updated_by"`
	UpdatedIP       *string    `json:"updated_ip,omitempty" db:"updated_ip" gorm:"type:inet"`
	UpdatedDevice   *string    `json:"updated_device,omitempty" db:"updated_device" gorm:"type:jsonb"`
	UpdatedSession  *uuid.UUID `json:"updated_session,omitempty" db:"updated_session"`
	UpdatedLocation *string    `json:"updated_location,omitempty" db:"updated_location" gorm:"type:jsonb"`
	
	DeletedAt       *time.Time `json:"deleted_at,omitempty" db:"deleted_at"`
	DeletedBy       *uuid.UUID `json:"deleted_by,omitempty" db:"deleted_by"`
	DeletedIP       *string    `json:"deleted_ip,omitempty" db:"deleted_ip" gorm:"type:inet"`
	DeletedDevice   *string    `json:"deleted_device,omitempty" db:"deleted_device" gorm:"type:jsonb"`
	DeletedSession  *uuid.UUID `json:"deleted_session,omitempty" db:"deleted_session"`
	DeletedLocation *string    `json:"deleted_location,omitempty" db:"deleted_location" gorm:"type:jsonb"`
	
	SourceSystem  string  `json:"source_system" db:"source_system" gorm:"size:50;default:reference_master"`
	ChangeReason  *string `json:"change_reason,omitempty" db:"change_reason" gorm:"type:text"`
	Version       int     `json:"version" db:"version" gorm:"default:1;not null"`
}

// TableName methods for GORM
func (Country) TableName() string { return "domain_reference_master_geopolitical.countries" }
func (Region) TableName() string { return "domain_reference_master_geopolitical.regions" }
func (Timezone) TableName() string { return "domain_reference_master_geopolitical.timezones" }
func (Language) TableName() string { return "domain_reference_master_geopolitical.languages" }